pipeline {

    agent any


    environment {

        DOCKER_REPO = "rohitpathare1204"
        IMAGE_TAG = "${BUILD_NUMBER}"

    }


    stages {


        stage('Checkout') {

            steps {

                git branch: 'master',
                    url: 'https://github.com/rohit-1204/python-fastapi-microservices.git'

            }

        }



        stage('Docker Login') {

            steps {

                withCredentials([
                    usernamePassword(
                        credentialsId: 'dockerhub-creds',
                        usernameVariable: 'DOCKER_USER',
                        passwordVariable: 'DOCKER_TOKEN'
                    )
                ]) {

                    sh '''
                    echo "$DOCKER_TOKEN" | docker login \
                    -u "$DOCKER_USER" \
                    --password-stdin
                    '''

                }

            }

        }



        stage('Build User Service') {

            steps {

                sh '''

                docker build \
                -t ${DOCKER_REPO}/user-service:${IMAGE_TAG} \
                ./user-service


                docker tag \
                ${DOCKER_REPO}/user-service:${IMAGE_TAG} \
                ${DOCKER_REPO}/user-service:latest

                '''

            }

        }



        stage('Build Product Service') {

            steps {

                sh '''

                docker build \
                -t ${DOCKER_REPO}/product-service:${IMAGE_TAG} \
                ./product-service


                docker tag \
                ${DOCKER_REPO}/product-service:${IMAGE_TAG} \
                ${DOCKER_REPO}/product-service:latest

                '''

            }

        }




        stage('Build Order Service') {

            steps {

                sh '''

                docker build \
                -t ${DOCKER_REPO}/order-service:${IMAGE_TAG} \
                ./order-service


                docker tag \
                ${DOCKER_REPO}/order-service:${IMAGE_TAG} \
                ${DOCKER_REPO}/order-service:latest

                '''

            }

        }




        stage('Push Docker Images') {

            steps {

                sh '''

                docker push ${DOCKER_REPO}/user-service:${IMAGE_TAG}
                docker push ${DOCKER_REPO}/user-service:latest


                docker push ${DOCKER_REPO}/product-service:${IMAGE_TAG}
                docker push ${DOCKER_REPO}/product-service:latest


                docker push ${DOCKER_REPO}/order-service:${IMAGE_TAG}
                docker push ${DOCKER_REPO}/order-service:latest

                '''

            }

        }




        stage('Docker Logout') {

            steps {

                sh '''
                docker logout
                '''

            }

        }

    }



    post {

        always {

            sh '''
            docker image prune -f
            '''

        }

    }

}